language: node_js
node_js:
    - '0.10'
script: npm run jsHint -- --failTaskOnError
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
deploy:
  provider: modulus
  api_key: MODULUS_KEY
  project_name: miscord
